# Generated by Django 5.1.3 on 2024-12-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_faculty_user_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='room_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='assigned_classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subject', to='core.classroom'),
        ),
    ]
