# Generated by Django 5.1.3 on 2024-12-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_classroom_room_title_subject_assigned_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='assigned_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subjects', to='core.classroom'),
        ),
    ]
