# Generated by Django 5.1.3 on 2024-12-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subject_assigned_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_split',
            field=models.BooleanField(default=False),
        ),
    ]
