# Generated by Django 5.1.3 on 2024-12-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timeslot_is_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_slot',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.timeslot'),
            preserve_default=False,
        ),
    ]
