# Generated by Django 5.1.3 on 2024-12-08 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_timetable_faculty_alter_timetable_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timeslot'),
        ),
        migrations.CreateModel(
            name='PracticalPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_pair', to='core.timeslot')),
                ('second_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_pair', to='core.timeslot')),
            ],
        ),
    ]
