# Generated by Django 5.1.3 on 2024-12-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_timeslot_is_original_alter_timetable_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
        ),
    ]
